# Generated by Django 4.2.6 on 2023-11-26 18:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_profile_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='date_of_birth',
        ),
    ]
