# Generated by Django 4.2.6 on 2023-10-20 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0002_image_url_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='url_user',
            field=models.URLField(default=models.URLField(max_length=2000), max_length=2000),
        ),
    ]
