# Generated by Django 4.2.6 on 2023-11-06 09:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('images', '0005_rename_user_url_image_website_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='private',
            field=models.BooleanField(default=True),
        ),
    ]
